# Generated by Django 4.0.1 on 2022-01-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_exam_id_alter_exam_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.value', unique=True),
        ),
    ]
