# Generated by Django 4.0.1 on 2022-01-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_exam_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstanse',
            new_name='BookInstance',
        ),
        migrations.DeleteModel(
            name='exam',
        ),
        migrations.DeleteModel(
            name='value',
        ),
    ]
